openapi: 3.0.3
info:
  title: '[WISdoM] Smartmeter Data Management Service'
  description: |
    This microservice allows the management of smart meter data that has been 
    written into the database.
    Furthermore, the service provides an endpoint allowing external services to
    write collected smart meter data into the database, either as a batch operation
    or writing single entries.
  version: 0.1.0
servers:
  - url: '/smartmeter-data'


tags:
  - name: reading
    description: |
      Operations that allow reading data series information

  - name: cud
    description: |
      Operations that allow C(reate)/(U)pdate/(D)elete operations

components:
  schemas:
    DataSeriesInformation:
      properties:
        id:
          type: string
          title: Smart Meter ID
          description: ID of the smart meter used to record the time series
        startDate:
          type: string
          format: date-time
          title: Time Series Start
          description: |
            The date and time of the first datapoint recorded in the time series
        endDate:
          type: string
          format: date-time
          title: Time Series End
          description: |
            The date and time of the last datapoint recorded in the time series
    Datapoint:
      properties:
        timestamp:
          type: string
          format: date-time
        value:
          type: number
          format: float
  responses:
    Error:
      description: An Error has occurred in the application or an invalid input has been provided
      content:
        application/problem+json:
          schema:
            type: object
            required:
              - type
              - status
              - title
              - detail
              - instance
            properties:
              type:
                type: string
              status:
                type: integer
              title:
                type: string
              detail:
                type: string
              instance:
                type: string
              error:
                type: string

    DataSeries:
      description: A data series that has been read from the database
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Datapoint'
        application/cbor:
          schema:
            type: string
        text/csv:
          schema:
            type: string
            pattern: '^timestamp,value\n((\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)*(Z|[\+-]\d{2}:\d{2})),(\d+(.\d+)?)(\n)?)+'

paths:
  /:
    get:
      summary: Get available data series
      description: |
        This endpoint returns information about the available smart meters and
        their data series
      tags:
        - reading
      responses:
        200:
          description: Data Series Information
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataSeriesInformation'
        204:
          description: No data series available

  /{data-series-id}:
    parameters:
      - in: path
        name: data-series-id
        description: |
          The ID of the Data Series as shown in the Data Series Information 
          response
        required: true
        schema:
          type: string
          minLength: 1

    get:
      summary: Read Timeseries
      description: |
        Retrieve data from the data series.
      parameters:
        - in: query
          name: from
          description: |
            A [ISO 8691] compliant 
            timestamp indicating the end of the handled data series excerpt. 
            The timestamp is used in a inclusive way.
            
            [ISO 8691]: https://en.wikipedia.org/wiki/ISO_8601
          allowEmptyValue: false
          schema:
            type: string
        - in: query
          name: until
          description: |
            A [ISO 8691] compliant 
            timestamp indicating the end of the handled data series excerpt. 
            The timestamp is used in a inclusive way.
            
            [ISO 8691]: https://en.wikipedia.org/wiki/ISO_8601
          allowEmptyValue: false
          schema:
            maximum: 1
            type: string
        - in: query
          name: format
          description: |
            The output wanted in the returned response
          schema:
            maximum: 1
            type: string
            default: json
            enum:
              - json
              - cbor
              - csv
      tags:
        - reading
      responses:
        200:
          $ref: '#/components/responses/DataSeries'

        206:
          $ref: '#/components/responses/DataSeries'

        400:
          $ref: '#/components/responses/Error'

        404:
          $ref: '#/components/responses/Error'
        416:
          $ref: '#/components/responses/Error'
    post:
      summary: Add Data to the Timeseries
      description: |

      tags:
        - cud
      requestBody:
        content:
          text/csv:
            schema:
              type: string
            example: |-
              ts,flow_rate
              2024-02-21T10:03:58+01:00,5
              2024-02-21T10:04:58+01:00,4.67
              2024-02-21T10:05:58+01:00,1.23
              2024-02-21T10:06:58+01:00,4.20
      responses:
        201:
          description: The Data has been added to the time series
    patch:
      summary: Replace Data in the Time series
      description: |

      tags:
        - cud
      parameters:
        - in: query
          name: from
          description: |
            A [ISO 8691] compliant 
            timestamp indicating the end of the handled data series excerpt. 
            The timestamp is used in a inclusive way.

            [ISO 8691]: https://en.wikipedia.org/wiki/ISO_8601
          allowEmptyValue: false
          schema:
            type: string
        - in: query
          name: until
          description: |
            A [ISO 8691] compliant 
            timestamp indicating the end of the handled data series excerpt. 
            The timestamp is used in a inclusive way.

            [ISO 8691]: https://en.wikipedia.org/wiki/ISO_8601
          allowEmptyValue: false
          schema:
            type: string
      requestBody:
        content:
          text/csv:
            schema:
              type: string
            example: |-
              ts,flow_rate
              2024-02-21T10:03:58+01:00,5
              2024-02-21T10:04:58+01:00,4.67
              2024-02-21T10:05:58+01:00,1.23
              2024-02-21T10:06:58+01:00,4.20
      responses:
        200:
          description: Data has been replaced
