openapi: 3.1.0
info: 
  title: SmartMeter Data API
  version: 2.0.0

servers: 
  - url: https://{wisdom-host}/api/smartmeter-data
    variables:
      wisdom-host:
        default: wisdom-demo.uol.de 
        description: The Server your WISdoM Instance is running on

tags:
  - name: Smartmeter
    description: These routes are usable for managing smartmeters
  - name: Timeseries
    description: These routes are usable for retrieving and uploading timeseries data
components: 
  schemas:
    Datapoint:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          description: RFC3339-compliant timestamp
        flowRate:
          type: number
          description: The recorded flow-rate
    SmartMeter:
      type: object
      required:
        - id
        - geometry
        - key
      properties:
        id:
          type: integer
          min: 0
          description: database-assigned id of the smartmeter
        geometry:
          type: object
          description: The Point Geometry of the SmartMeters location
          externalDocs:
            url: http://geojson.org/geojson-spec.html#id2
        name:
          type: string
          description: the name of the smart meter (e.g., a external identifier)
        key:
          type: string
          description: a identifier of the smart meter for geospatial applications
        additionalProperties:
          type: object
          description: additional properties assigned to the smart meter
          additionalProperties: true
        

  securitySchemes:
    wisdom:
      type: openIdConnect
      openIdConnectUrl: /api/auth/.well-known/openid-configuration

paths:
  /meters:
    get:
      operationId: smartmeter-list
      summary: List all SmartMeters
      security:
        - wisdom-host: ["smartmeter:read"]
      tags:
        - Smartmeter
      responses:
        200:
          description: Smartmeter List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SmartMeter'
    
    put:
      operationId: create-smartmeter
      summary: Create SmartMeter
      security:
        - wisdom-host: ["smartmeter:write"]
      tags:
        - Smartmeter
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - latitude
                - longitude
              properties:
                name:
                  type: string
                  description: the name of the smart meter
                key:
                  type: string
                  description: |
                    the geodata key of the smart meter.
                    If not supplied,it will be autogenerated by the service
                latitude:
                  type: number
                  description: |
                    The latitude of the smartmeters location
                longitude:
                  type: number
                  description: |
                    The longiture of the smartmeters location
                additionalProperties:
                  type: object
                  additionalProperties: true
      responses:
        200:
          description: Smartmeter Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmartMeter'

  /meters/{meterKey}:
    parameters:
      - in: path
        name: meterKey
        required: true
        schema:
          type: string

    get:
      operationId: smartmeter-details
      summary: Get Smartmeter Details
      security:
        - wisdom-host: ["smartmeter:read"]
      tags:
        - Smartmeter
      responses:
        200:
          description: Smartmeter Details
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/SmartMeter'
                  - type: object
                    properties:
                      firstRecordTimestamp:
                        type: string
                        format: date-time
                        description: the timestamp of the first available data point
                      availableRecords:
                        type: integer
                        min: 0
                        description: the number of records assigned to the smart meter

    patch:
      operationId: update-smartmeter
      summary: Update Smartmeter
      description: |
        When updating the location of the smart meter using the `longitude` and
        `latitude` parameters you need to specify both values, as updating one
        coordinate only is not allowed to decrease the amount of accidential
        changes being made.
      security:
        - wisdom-host: ["smartmeter:write"]
      tags:
        - Smartmeter
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  title: Update Everything
                  properties:
                    name:
                      type: string
                    latitude:
                      type: number
                    longitude:
                      type: number
                    additionalProperties:
                      type: object
                      additionalProperties: true
                - type: object
                  title: Update Coordinates Only
                  properties:
                    latitude:
                      type: number
                    longitude:
                      type: number
                - type: object
                  title: Update Name Only
                  properties:
                    name:
                      type: string
                - type: object
                  title: Update Additional Properties Only
                  properties:
                    additionalProperties:
                      type: object
                      additionalProperties: true
                - type: object
                  title: Update Name + Additional Properties
                  properties:
                    name:
                      type: string
                    additionalProperties:
                      type: object
                      additionalProperties: true
                - type: object
                  title: Update Name + Coordinates
                  properties:
                    name:
                      type: string
                    latitude:
                      type: number
                    longitude:
                      type: number
                - type: object
                  title: Update Coordinates + Additional Properties
                  properties:
                    latitude:
                      type: number
                    longitude:
                      type: number
                    additionalProperties:
                      type: object
                      additionalProperties: true

      responses:
        200:
          description: Smartmeter Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmartMeter'
      
    delete:
      operationId: delete-smartmeter
      summary: Delete Smartmeter
      description: |
        Deleting a smartmeter results in deleting all entries in the timeseries
        for it. The deleted data is not restorable
      security:
        - wisdom-host: ["smartmeter:delete"]
      tags:
        - Smartmeter
      responses:
        204:
          description: Smartmeter Deleted
  
  /data/{meterID}:
    parameters:
      - in: path
        name: meterID
        required: true
        schema:
          type: integer
    
    get:
      operationId: get-timeseries
      summary: Get Timeseries
      description: |
        Retrieve the timeseries for the smartmeter
      security:
        - wisdom-host: ["smartmeter:delete"]
      tags:
        - Timeseries
      parameters:
        - in: query
          name: from
          schema:
            type: string
            format: date-time
        - in: query
          name: until
          schema:
            type: string
            format: date-time
        - in: header
          name: Accept
          description: |
            Control the format in which the endpoint returns the data. If no
            header is explicitly set or the format is not supported, the service
            returns a JSON representation of the data
          required: false
          schema:
            type: string
            enum:
              - application/json
              - text/csv
              - application/x-ndjson
            default: application/json
      responses:
        200:
          description: Timeseries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Datapoint'
            application/x-ndjson:
              schema:
                description: |
                  The ND-JSON format encapsulates each element of an array as
                  a singular json object.
                  The array entires are delmitied by a newline character
                type: object
            text/csv:
              schema:
                type: string
                description: |
                  The CSV encoding of the requested datapoints

    post:
      operationId: add-datapoints
      summary: Add Datapoints
      security:
        - wisdom-host: ["smartmeter:write"]
      tags:
        - Timeseries
      requestBody:
        content:
          text/csv:
            schema:
              type: object
              properties:
                time:
                  type: string
                  format: date-time
                flow_rate:
                  type: number
            example: |
              timestamp,flow_rate
              2025-01-07T11:39:50+00:00,2
              2025-01-07T11:40:00+00:00,1
              2025-01-07T11:40:10+00:00,0.12
              2025-01-07T11:40:20+00:00,0.26
              2025-01-07T11:40:30+00:00,1.457
      responses:
        201:
          description: |
            *Datapoints Added*

            The datapoints from the CSV request body have been imported.
            The `invalidDatapoints` field will be omitted from the request, if
            there are no invalid datapoints in the request body.
          content:
            application/json:
              schema:
                type: object
                properties:
                  insertedDatapoints:
                    type: integer
                    description: number of inserted datapoints
                  invalidDatapoints:
                    type: array
                    description: line numbers of invalid datapoints
                    items:
                      type: integer
  